MODEL:
  NAME: "deeplab_resnet101"
  WEIGHTS: "https://download.pytorch.org/models/resnet101-5d3b4d8f.pth"
  FREEZE_BN: False
DATASETS:
  SOURCE_TRAIN: "cityscapes_train_soft"
  TEST: "cityscapes_val"
INPUT:
  SOURCE_INPUT_SIZE_TRAIN: (1024, 512)
  INPUT_SCALES_TRAIN: (0.5, 1.5)
  HORIZONTAL_FLIP_PROB_TRAIN: 0.5
  BRIGHTNESS: 0.5
  CONTRAST: 0.5
  SATURATION: 0.5
  HUE: 0.2
  RANDOMAPPLY: 1.0
  GRAYSCALE: 0.2
  GAUSSIANBLUR: True
SOLVER:
  BASE_LR: 5e-4
  MAX_ITER: 90000
  STOP_ITER: 90000
  BATCH_SIZE: 8
